frr version 10.7
frr defaults traditional
hostname leaf1
service integrated-vtysh-config
!
router bgp 65101
 bgp router-id 11.11.11.11
 no bgp ebgp-requires-policy
 neighbor 10.201.11.2 remote-as 65000
 neighbor 10.201.11.2 timers 3 9
 neighbor 10.201.21.2 remote-as 65000
 neighbor 10.201.21.2 timers 3 9
 !
 address-family ipv4 unicast
  network 10.201.101.0/29
  maximum-paths 2
  neighbor 10.201.11.2 activate
  neighbor 10.201.21.2 activate
 exit-address-family
!
