frr version 10.7
frr defaults traditional
hostname spine1
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.201.11.3 remote-as 65101
 neighbor 10.201.11.3 timers 3 9
 neighbor 10.201.12.3 remote-as 65102
 neighbor 10.201.12.3 timers 3 9
 !
 address-family ipv4 unicast
  neighbor 10.201.11.3 activate
  neighbor 10.201.12.3 activate
 exit-address-family
!
