frr version 10.7
frr defaults traditional
hostname leaf2
service integrated-vtysh-config
!
router bgp 65102
 bgp router-id 22.22.22.22
 no bgp ebgp-requires-policy
 neighbor 10.201.12.2 remote-as 65000
 neighbor 10.201.12.2 timers 3 9
 neighbor 10.201.22.2 remote-as 65000
 neighbor 10.201.22.2 timers 3 9
 !
 address-family ipv4 unicast
  network 10.201.102.0/29
  maximum-paths 2
  neighbor 10.201.12.2 activate
  neighbor 10.201.22.2 activate
 exit-address-family
!
